import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

// Parse JSON request bodies (increased limit to support rich ERP data snapshots)
app.use(express.json({ limit: '10mb' }));

// Initialize GoogleGenAI SDK lazily and securely on request or start
// We use the recommended 'gemini-3.5-flash' model
let aiClient: GoogleGenAI | null = null;

function getAiClient() {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.warn("WARNING: GEMINI_API_KEY is not defined in the environment secrets. The AI Assistant fallback mode is active.");
      return null;
    }
    aiClient = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

// API Routes FIRST
app.get('/api/health', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});

// Generic text generation endpoint for SmartTable (AI Summary, Forecast, Recommendations)
app.post('/api/gemini/generate', async (req, res) => {
  try {
    const { prompt, temperature = 0.4 } = req.body;

    if (!prompt) {
      res.status(400).json({ error: 'Prompt parameter is required.' });
      return;
    }

    const ai = getAiClient();
    if (!ai) {
      // Offline fallback
      setTimeout(() => {
        res.json({
          text: `[Offline Mode Fallback] Mock analysis outcome for query:\n"${prompt.substring(0, 60)}..."\n\nConfigure GEMINI_API_KEY inside Settings > Secrets to enable actual intelligence logic.`
        });
      }, 800);
      return;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: prompt,
      config: {
        temperature: Number(temperature),
      }
    });

    res.json({ text: response.text || "No output generated by AI model." });
  } catch (error: any) {
    console.error("Gemini Generate Route Error: ", error);
    res.status(500).json({ error: error?.message || 'Failure occurred during backend text generation.' });
  }
});

// Endpoint for the AI Operations Assistant
app.post('/api/gemini/chat', async (req, res) => {
  try {
    const { message, chatHistory, erpState } = req.body;

    if (!message) {
      res.status(400).json({ error: 'Message parameter is required.' });
      return;
    }

    const ai = getAiClient();
    
    // Fallback if API Key not found
    if (!ai) {
      // Mock dark luxury AI response when key isn't set up yet
      setTimeout(() => {
        res.json({
          text: `### [ILLUMINIST OS Offline Mode]

I detected that the \`GEMINI_API_KEY\` is not present in your Workspace Secrets. To experience full, real-time advanced operations reasoning, configure your key inside the **Settings > Secrets** panel.

Here is an analysis based on local client diagnostics:
- **Inventory Standing:** ${erpState?.materials?.length || 0} Materials loaded.
- **Stock Alert:** Identified several items with quantities below safety thresholds. Consider reviewing fabric reserves.
- **Retail Force:** Active collections stand at ${erpState?.products?.length || 0} master items.`
        });
      }, 1000);
      return;
    }

    // Build the rich context prompt representing ILLUMINIST OS
    const systemInstruction = `You are 'ILLUMINIST AI', the Chief of Staff for ILLUMINIST OS — an AI-powered multi-business operating system for a founder running several businesses under one holding. Adapt to whichever business the owner is currently working in; never assume a single industry.
Your objective is to help the owner optimize supply chain and operations, understand margins, analyze campaign returns, suggest reorders, and highlight operational risks across the business with absolute precision.

You have access to the current live relational ERP database snapshot provided below:

--- MATERIALS IN STOCK ---
${JSON.stringify(erpState?.computedMaterials || erpState?.materials || [], null, 2)}

--- SAMPLES IN DEVELOPMENT ---
${JSON.stringify(erpState?.computedSamples || erpState?.samples || [], null, 2)}

--- ACTIVE PRODUCTION BATCHES ---
${JSON.stringify(erpState?.computedProduction || erpState?.production || [], null, 2)}

--- MASTER PRODUCTS (WITH LIVE HPP & NET MARGINS) ---
${JSON.stringify(erpState?.computedProducts || erpState?.products || [], null, 2)}

--- INVENTORY BY SIZE VARIANT ---
${JSON.stringify(erpState?.computedVariants || erpState?.variants || [], null, 2)}

--- CHANNELS & SALES JOURNAL ---
${JSON.stringify(erpState?.computedSales || erpState?.sales || [], null, 2)}

--- ADS CAMPAIGN ROI ---
${JSON.stringify(erpState?.computedAds || erpState?.adsCampaigns || [], null, 2)}

--- KOL INFLUENCE TRACKING ---
${JSON.stringify(erpState?.computedKols || erpState?.kols || [], null, 2)}

--- SUPPLIERS & CONTACTS ---
${JSON.stringify(erpState?.suppliers || [], null, 2)}

Your guidelines:
1. Always calculate exact figures when asked. Avoid hand-wavy or vague summaries. CITE real Material IDs, SKUs, and exact remaining stocks.
2. In your formatting, present structured, luxury-tech layouts: use clean markdown headers, tables, bullet lists, and code scopes for metrics.
3. Be cold, concise, elite, and deeply strategic. You are a tool for professional fashion directors.
4. If asked to "recommend material reorders", look for materials where remaining quantity is less than minimum stock. Recommend reordering a volume that brings stock back to minimum + 20% margin, and suggest who the Preferred supplier is.
5. If asked about profitability, calculate which products yield the highest net profit margins (%), which have the lowest HPP, and highlight if high ads spend is cannibalizing unit profits.
6. Speak directly and professionally. No fluff.`;

    // Map chatHistory to standard Gemini parts format
    const contents = chatHistory ? chatHistory.map((h: any) => ({
      role: h.role === 'user' ? 'user' : 'model',
      parts: [{ text: h.content }]
    })) : [];

    // Append the current message
    contents.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: contents,
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.2, // lower temperature for analytical ERP precision
      }
    });

    const text = response.text || "Examine system diagnostic - no response generated.";
    res.json({ text });

  } catch (error: any) {
    console.error("Gemini Assistant Route Error: ", error);
    res.status(500).json({ error: error?.message || 'Failure occurred during backend reasoning.' });
  }
});

// Setup dev server or static serve
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    // Serve static frontend build
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`ILLUMINIST OS fullstack server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
